export const API_ERROR_TEXTS = {
  network: 'Нет соединения с GREEN-API',
  emptyResponse: 'GREEN-API вернул пустой ответ',
  invalidResponse: 'GREEN-API вернул некорректный ответ',
  invalidApiUrl: 'Некорректный apiUrl',
  sendFailed: 'Не удалось отправить сообщение',
  badRequest: 'Некорректный запрос',
  unauthorized: 'Неверный idInstance или apiTokenInstance',
  notFound: 'Некорректный адрес метода — проверьте apiUrl',
  tooManyRequests: 'Слишком много запросов, попробуйте позже',
  quotaExceeded: 'Исчерпан лимит тарифа',
  messengerRateLimit: 'Мессенджер временно ограничил поиск контактов — попробуйте через несколько часов',
  serverUnavailable: 'Сервер GREEN-API недоступен',
  webhookSet: 'В настройках инстанса задан webhookUrl — очистите его в личном кабинете GREEN-API и подождите минуту',
  instanceStarting: 'Инстанс запускается, попробуйте через минуту',
  instanceExpired: 'Срок действия инстанса истёк — продлите тариф в личном кабинете',
  instanceDeleted: 'Инстанс удалён',
  unknown: (status: number) => `Ошибка GREEN-API (${status})`,
};
